title: jaszai.dev
baseURL: http://localhost:1313/

# Locale
locale: hu-hu
defaultContentLanguage: hu

# Content
summaryLength: 125
readingTimeSpeed: 180

# Extra config
enableRobotsTXT: true
disableHugoGeneratorInject: true

module:
    imports:
        - path: github.com/adityatelange/hugo-PaperMod
